import { Property, Testimonial } from "./types";

export const properties: Property[] = [
  {
    id: "prop-001",
    title: "Luxury 3BHK Apartment",
    type: "residential",
    category: "buy",
    price: 8500000,
    priceLabel: "₹85 Lakhs",
    area: 1450,
    bhk: 3,
    location: "Sector 21, Faridabad",
    sector: "Sector 21",
    description:
      "A stunning 3BHK apartment in the heart of Sector 21 with modern amenities, excellent connectivity, and breathtaking views. Fully vastu-compliant with premium fittings throughout.",
    images: [
      "https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=800&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=800&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800&auto=format&fit=crop",
    ],
    amenities: ["Swimming Pool", "Gym", "24/7 Security", "Power Backup", "Club House"],
    floor: 8,
    totalFloors: 14,
    parking: true,
    facing: "East",
    furnishing: "semi-furnished",
    featured: true,
  },
  {
    id: "prop-002",
    title: "Commercial Office Space",
    type: "commercial",
    category: "rent",
    price: 45000,
    priceLabel: "₹45,000/month",
    area: 2200,
    location: "Neelam Chowk, Faridabad",
    sector: "Neelam Chowk",
    description:
      "Premium office space in Neelam Chowk commercial hub. Ground floor with high footfall, dedicated parking, and modern infrastructure. Ideal for corporate offices and showrooms.",
    images: [
      "https://images.unsplash.com/photo-1497366216548-37526070297c?w=800&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1497366754035-f200968a6e72?w=800&auto=format&fit=crop",
    ],
    amenities: ["Dedicated Parking", "Power Backup", "High-Speed Internet", "AC", "24/7 Security"],
    floor: 0,
    parking: true,
    furnishing: "furnished",
    featured: true,
  },
  {
    id: "prop-003",
    title: "Industrial Plot — IMT Faridabad",
    type: "industrial",
    category: "buy",
    price: 25000000,
    priceLabel: "₹2.5 Crores",
    area: 5000,
    location: "IMT Faridabad, Sector 58",
    sector: "Sector 58",
    description:
      "Prime industrial plot in IMT Faridabad with all clearances. Excellent road connectivity to NH-48. Suitable for manufacturing, warehousing, and logistics operations.",
    images: [
      "https://images.unsplash.com/photo-1581094794329-c8112a89af12?w=800&auto=format&fit=crop",
    ],
    amenities: ["NH-48 Access", "3-Phase Power", "Water Connection", "Boundary Wall"],
    featured: true,
  },
  {
    id: "prop-004",
    title: "2BHK Builder Floor",
    type: "residential",
    category: "rent",
    price: 18000,
    priceLabel: "₹18,000/month",
    area: 900,
    bhk: 2,
    location: "Sector 46, Faridabad",
    sector: "Sector 46",
    description:
      "Spacious 2BHK builder floor on first floor in a peaceful residential colony. Well-ventilated rooms with modular kitchen and attached bathrooms.",
    images: [
      "https://images.unsplash.com/photo-1493809842364-78817add7ffb?w=800&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800&auto=format&fit=crop",
    ],
    amenities: ["Power Backup", "Water Supply", "Parking", "Security"],
    floor: 1,
    totalFloors: 3,
    parking: true,
    facing: "West",
    furnishing: "unfurnished",
  },
  {
    id: "prop-005",
    title: "Showroom Space on NH-48",
    type: "commercial",
    category: "lease",
    price: 85000,
    priceLabel: "₹85,000/month",
    area: 3500,
    location: "NH-48, Faridabad",
    sector: "NH-48",
    description:
      "High-visibility showroom space on National Highway 48 with massive frontage. Ideal for automobile showrooms, furniture stores, and retail brands. Ground + Mezzanine.",
    images: [
      "https://images.unsplash.com/photo-1441986300917-64674bd600d8?w=800&auto=format&fit=crop",
    ],
    amenities: ["Highway Frontage", "Ample Parking", "Power Backup", "Loading Bay"],
  },
  {
    id: "prop-006",
    title: "Residential Plot — Sector 16",
    type: "residential",
    category: "buy",
    price: 12000000,
    priceLabel: "₹1.2 Crores",
    area: 200,
    location: "Sector 16, Faridabad",
    sector: "Sector 16",
    description:
      "Ready-to-build residential plot in posh Sector 16 with approved map. Corner plot with excellent vastu alignment. Park facing, peaceful locality.",
    images: [
      "https://images.unsplash.com/photo-1500382017468-9049fed747ef?w=800&auto=format&fit=crop",
    ],
    amenities: ["Park Facing", "Corner Plot", "Approved Map", "Vastu Aligned"],
    facing: "North-East",
  },
  {
    id: "prop-007",
    title: "3BHK Villa with Garden",
    type: "residential",
    category: "buy",
    price: 18500000,
    priceLabel: "₹1.85 Crores",
    area: 2800,
    bhk: 3,
    location: "Sector 15, Faridabad",
    sector: "Sector 15",
    description:
      "Elegant 3BHK independent villa with private garden and rooftop terrace. Premium woodwork, designer bathrooms, modular kitchen. Gated community with 24/7 security.",
    images: [
      "https://images.unsplash.com/photo-1613977257363-707ba9348227?w=800&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=800&auto=format&fit=crop",
    ],
    amenities: ["Private Garden", "Terrace", "Servant Quarter", "3 Car Parking", "Club House"],
    floor: 0,
    totalFloors: 2,
    parking: true,
    facing: "East",
    furnishing: "furnished",
    featured: true,
  },
  {
    id: "prop-008",
    title: "Factory Shed — IMT",
    type: "industrial",
    category: "lease",
    price: 120000,
    priceLabel: "₹1.2 Lakhs/month",
    area: 8000,
    location: "IMT Faridabad, Sector 59",
    sector: "Sector 59",
    description:
      "Ready-to-use factory shed with 10-meter height, overhead crane provision, and excellent road connectivity. Three-phase power with 200 KVA transformer. Immediate possession.",
    images: [
      "https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?w=800&auto=format&fit=crop",
    ],
    amenities: ["Overhead Crane Provision", "3-Phase Power", "Loading Dock", "Security Cabin"],
  },
  {
    id: "prop-009",
    title: "2BHK Flat — NIT Faridabad",
    type: "residential",
    category: "buy",
    price: 4500000,
    priceLabel: "₹45 Lakhs",
    area: 850,
    bhk: 2,
    location: "NIT, Faridabad",
    sector: "NIT",
    description:
      "Affordable 2BHK flat in well-established NIT area. Metro connectivity nearby, close to schools, hospitals, and markets. Investment-grade property with great rental yield.",
    images: [
      "https://images.unsplash.com/photo-1560185007-cde436f6a4d0?w=800&auto=format&fit=crop",
    ],
    amenities: ["Metro Nearby", "Lift", "Power Backup", "24/7 Water"],
    floor: 4,
    totalFloors: 8,
    parking: true,
    furnishing: "unfurnished",
  },
  {
    id: "prop-010",
    title: "Commercial Shop — Old Faridabad",
    type: "commercial",
    category: "sell",
    price: 3500000,
    priceLabel: "₹35 Lakhs",
    area: 280,
    location: "Old Faridabad",
    sector: "Old Faridabad",
    description:
      "Prime ground-floor commercial shop in Old Faridabad with massive footfall. Corner unit with dual frontage. Perfect for retail, pharmacy, or fast-food franchise.",
    images: [
      "https://images.unsplash.com/photo-1604328698692-f76ea9498e76?w=800&auto=format&fit=crop",
    ],
    amenities: ["Corner Location", "High Footfall", "Ground Floor", "Storage Room"],
    floor: 0,
  },
  {
    id: "prop-011",
    title: "4BHK Penthouse",
    type: "residential",
    category: "buy",
    price: 32000000,
    priceLabel: "₹3.2 Crores",
    area: 4200,
    bhk: 4,
    location: "Sector 28, Faridabad",
    sector: "Sector 28",
    description:
      "Spectacular penthouse spanning the entire top floor with panoramic views of Aravalli Hills. Private terrace, home theatre, smart home automation, and luxury finishes throughout.",
    images: [
      "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=800&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=800&auto=format&fit=crop",
    ],
    amenities: ["Private Terrace", "Home Theatre", "Smart Home", "Infinity Pool Access", "4 Parking"],
    floor: 22,
    totalFloors: 22,
    parking: true,
    facing: "South-West",
    furnishing: "furnished",
    featured: true,
  },
  {
    id: "prop-012",
    title: "Office Space — BPTP Park",
    type: "commercial",
    category: "rent",
    price: 65000,
    priceLabel: "₹65,000/month",
    area: 1800,
    location: "BPTP Park, Faridabad",
    sector: "BPTP",
    description:
      "Grade-A office space in prestigious BPTP Business Park. Fully furnished with collaborative workspaces, meeting rooms, and cafeteria access. Immediate fit-out available.",
    images: [
      "https://images.unsplash.com/photo-1568992687947-868a62a9f521?w=800&auto=format&fit=crop",
    ],
    amenities: ["Cafeteria", "Conference Rooms", "High-Speed Internet", "Valet Parking", "24/7 AC"],
    floor: 5,
    parking: true,
    furnishing: "furnished",
  },
  {
    id: "prop-013",
    title: "Warehouse — Industrial Sector",
    type: "industrial",
    category: "rent",
    price: 75000,
    priceLabel: "₹75,000/month",
    area: 12000,
    location: "Sector 58, Faridabad",
    sector: "Sector 58",
    description:
      "Modern logistics warehouse with high ceiling, dock-level loading, CCTV surveillance, and fire suppression system. Excellent connectivity to Delhi-Agra Expressway.",
    images: [
      "https://images.unsplash.com/photo-1553413077-190dd305871c?w=800&auto=format&fit=crop",
    ],
    amenities: ["Dock-Level Loading", "CCTV", "Fire Suppression", "Expressway Access"],
  },
  {
    id: "prop-014",
    title: "Studio Apartment",
    type: "residential",
    category: "rent",
    price: 12000,
    priceLabel: "₹12,000/month",
    area: 480,
    bhk: 1,
    location: "Sector 14, Faridabad",
    sector: "Sector 14",
    description:
      "Compact studio apartment ideal for working professionals. Fully furnished with modular kitchen, Wi-Fi infrastructure, and laundry facility on premises.",
    images: [
      "https://images.unsplash.com/photo-1536376072261-38c75010e6c9?w=800&auto=format&fit=crop",
    ],
    amenities: ["Furnished", "Wi-Fi Ready", "Laundry", "Security"],
    floor: 2,
    furnishing: "furnished",
  },
  {
    id: "prop-015",
    title: "Builder Floor — Sector 46",
    type: "residential",
    category: "sell",
    price: 7800000,
    priceLabel: "₹78 Lakhs",
    area: 1200,
    bhk: 3,
    location: "Sector 46, Faridabad",
    sector: "Sector 46",
    description:
      "Independent builder floor with separate entry. Stilt parking, modular kitchen, premium tiles, and RO water system. Ready possession, clear title.",
    images: [
      "https://images.unsplash.com/photo-1484154218962-a197022b5858?w=800&auto=format&fit=crop",
    ],
    amenities: ["Stilt Parking", "Separate Entry", "RO Water", "Power Backup"],
    floor: 2,
    totalFloors: 4,
    parking: true,
    furnishing: "semi-furnished",
  },
  {
    id: "prop-016",
    title: "Industrial Land — Sector 59",
    type: "industrial",
    category: "buy",
    price: 45000000,
    priceLabel: "₹4.5 Crores",
    area: 10000,
    location: "Sector 59, Faridabad",
    sector: "Sector 59",
    description:
      "Large industrial land parcel with clear title and all statutory approvals. Surrounded by established manufacturing units. Ideal for greenfield industrial project.",
    images: [
      "https://images.unsplash.com/photo-1504307651254-35680f356dfd?w=800&auto=format&fit=crop",
    ],
    amenities: ["Clear Title", "All Approvals", "Road Access", "Power Infrastructure"],
  },
  {
    id: "prop-017",
    title: "Retail Space — Crown Interiors Mall",
    type: "commercial",
    category: "lease",
    price: 55000,
    priceLabel: "₹55,000/month",
    area: 650,
    location: "Crown Interiors Mall, Faridabad",
    sector: "NH-48",
    description:
      "Premium retail unit in Crown Interiors Mall, Faridabad's premier furniture and home decor destination. High-traffic location with dedicated customer parking.",
    images: [
      "https://images.unsplash.com/photo-1555529669-e69e7aa0ba9a?w=800&auto=format&fit=crop",
    ],
    amenities: ["Mall Management", "Dedicated Parking", "Power Backup", "CCTV"],
    floor: 1,
  },
  {
    id: "prop-018",
    title: "3BHK Independent House",
    type: "residential",
    category: "sell",
    price: 15500000,
    priceLabel: "₹1.55 Crores",
    area: 2100,
    bhk: 3,
    location: "Sector 21, Faridabad",
    sector: "Sector 21",
    description:
      "Beautifully maintained independent house with lush front lawn, servant quarter, and double car garage. Quiet residential pocket with excellent neighbourhood.",
    images: [
      "https://images.unsplash.com/photo-1568605114967-8130f3a36994?w=800&auto=format&fit=crop",
    ],
    amenities: ["Front Lawn", "Servant Quarter", "Double Garage", "RO System", "Generator"],
    floor: 0,
    totalFloors: 2,
    parking: true,
    facing: "North",
    furnishing: "unfurnished",
  },
  {
    id: "prop-019",
    title: "Co-Working Office — Sector 15",
    type: "commercial",
    category: "rent",
    price: 8000,
    priceLabel: "₹8,000/seat/month",
    area: 3200,
    location: "Sector 15, Faridabad",
    sector: "Sector 15",
    description:
      "Modern co-working facility with hot desks, private cabins, meeting pods, and event space. Community-driven environment with high-speed internet and unlimited refreshments.",
    images: [
      "https://images.unsplash.com/photo-1497215842964-222b430dc094?w=800&auto=format&fit=crop",
    ],
    amenities: ["Hot Desks", "Private Cabins", "Meeting Pods", "High-Speed Internet", "Refreshments"],
    floor: 2,
    furnishing: "furnished",
  },
  {
    id: "prop-020",
    title: "2BHK New Launch Apartment",
    type: "residential",
    category: "buy",
    price: 6200000,
    priceLabel: "₹62 Lakhs",
    area: 1050,
    bhk: 2,
    location: "Sector 28, Faridabad",
    sector: "Sector 28",
    description:
      "New launch ready-to-move apartment in a gated township. Vastu-compliant, EV charging points, solar rooftop, and rainwater harvesting. RERA approved.",
    images: [
      "https://images.unsplash.com/photo-1571939228382-b2f2b585ce15?w=800&auto=format&fit=crop",
    ],
    amenities: ["RERA Approved", "EV Charging", "Solar Rooftop", "Kids Play Area", "Gym"],
    floor: 6,
    totalFloors: 18,
    parking: true,
    facing: "South-East",
    furnishing: "unfurnished",
    featured: true,
  },
];

export const testimonials: Testimonial[] = [
  {
    id: "t1",
    name: "Rajesh Sharma",
    location: "Sector 21, Faridabad",
    propertyType: "3BHK Apartment",
    quote:
      "OM Estate made our home-buying journey seamless. Their knowledge of Faridabad's property market is unmatched. We found our dream home within two weeks!",
    rating: 5,
  },
  {
    id: "t2",
    name: "Priya Mehta",
    location: "BPTP Park, Faridabad",
    propertyType: "Commercial Office",
    quote:
      "Relocating our office was stressful until we connected with OM Estate. They found us the perfect space within our budget and negotiated excellent lease terms.",
    rating: 5,
  },
  {
    id: "t3",
    name: "Suresh Agarwal",
    location: "IMT Faridabad",
    propertyType: "Industrial Plot",
    quote:
      "For industrial property in IMT, OM Estate is the best. Complete transparency, all paperwork sorted, and they connected us with the right authorities. Highly recommended.",
    rating: 5,
  },
];

export const getFeaturedProperties = () => properties.filter((p) => p.featured);

export const getPropertyById = (id: string) => properties.find((p) => p.id === id);

export const getSimilarProperties = (property: Property, count = 3) =>
  properties
    .filter((p) => p.id !== property.id && p.type === property.type)
    .slice(0, count);
